---

- name: "Create required directories in /etc/letsencrypt"
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x
  with_items:
  - account
  - certs
  - csrs
  - keys
  - server/.well-known/acme-challenge

- name: "Start python webserver for a specified time"
  ansible.builtin.shell:
    cmd: "timeout 150 python3 -m http.server 80 &"
    chdir: /etc/letsencrypt/server/

- name: "Generate a Let's Encrypt account key"
  shell: "if [ ! -f {{ letsencrypt_account_key }} ]; then openssl genrsa 4096 | tee {{ letsencrypt_account_key }}; fi"

- name: "Generate Let's Encrypt private key"
  shell: "openssl genrsa 4096 | tee /etc/letsencrypt/keys/{{ domain_name }}.key"

- name: "Start subtask for each domain"
  include_tasks: single_domain.yaml
  with_items:
  - "{{ base_domain }}"
  - "matrix.{{ base_domain }}"
  - "jitsi.{{ base_domain }}"
  - "riot.{{ base_domain }}"
  loop_control:
    loop_var: single_domain
